#include "token.h"

const char *const token_type_names[] = {
	// Literals
	[TOKEN_TYPE_NUMBER] = "number",
	[TOKEN_TYPE_CHARACTER] = "character",
	[TOKEN_TYPE_STRING] = "string",
	[TOKEN_TYPE_IDENTIFIER] = "identifier",
	// Keywords
	[TOKEN_TYPE_MODULE] = "module",
	[TOKEN_TYPE_IMPORT] = "import",
	[TOKEN_TYPE_VAR] = "var",
	[TOKEN_TYPE_FUNC] = "func",
	[TOKEN_TYPE_TYPE] = "type",
	[TOKEN_TYPE_STRUCT] = "struct",
	[TOKEN_TYPE_TRAIT] = "trait",
	[TOKEN_TYPE_CASES] = "cases",
	[TOKEN_TYPE_EMBED] = "embed",
	[TOKEN_TYPE_PUB] = "pub",
	[TOKEN_TYPE_MUT] = "mut",
	[TOKEN_TYPE_OWNED] = "owned",
	[TOKEN_TYPE_WEAK] = "weak",
	[TOKEN_TYPE_AS] = "as",
	[TOKEN_TYPE_IS] = "is",
	[TOKEN_TYPE_BOOLEAN_AND] = "and",
	[TOKEN_TYPE_BOOLEAN_OR] = "or",
	[TOKEN_TYPE_BOOLEAN_XOR] = "xor",
	[TOKEN_TYPE_BOOLEAN_NOT] = "not",
	[TOKEN_TYPE_RETURN] = "return",
	[TOKEN_TYPE_BREAK] = "break",
	[TOKEN_TYPE_CONTINUE] = "continue",
	[TOKEN_TYPE_NEXT] = "next",
	[TOKEN_TYPE_DO] = "do",
	[TOKEN_TYPE_WHILE] = "while",
	[TOKEN_TYPE_FOR] = "for",
	[TOKEN_TYPE_IN] = "in",
	[TOKEN_TYPE_THRU] = "thru",
	[TOKEN_TYPE_UNTIL] = "until",
	[TOKEN_TYPE_BY] = "by",
	[TOKEN_TYPE_IF] = "if",
	[TOKEN_TYPE_ELSE] = "else",
	[TOKEN_TYPE_SWITCH] = "switch",
	[TOKEN_TYPE_CASE] = "case",
	[TOKEN_TYPE_DEFAULT] = "default",
	// Operators
	[TOKEN_TYPE_DOT] = ".",
	[TOKEN_TYPE_COMMA] = ",",
	[TOKEN_TYPE_COLON] = ":",
	[TOKEN_TYPE_SEMICOLON] = ";",
	[TOKEN_TYPE_LEFT_PARENTHESIS] = "(",
	[TOKEN_TYPE_RIGHT_PARENTHESIS] = ")",
	[TOKEN_TYPE_LEFT_BRACKET] = "[",
	[TOKEN_TYPE_RIGHT_BRACKET] = "]",
	[TOKEN_TYPE_LEFT_BRACE] = "{",
	[TOKEN_TYPE_RIGHT_BRACE] = "}",
	[TOKEN_TYPE_PLUS_ASSIGN] = "+=",
	[TOKEN_TYPE_PLUS] = "+",
	[TOKEN_TYPE_ARROW] = "->",
	[TOKEN_TYPE_MINUS_ASSIGN] = "-=",
	[TOKEN_TYPE_MINUS] = "-",
	[TOKEN_TYPE_TIMES_ASSIGN] = "*=",
	[TOKEN_TYPE_TIMES] = "*",
	[TOKEN_TYPE_DIVIDE_ASSIGN] = "/=",
	[TOKEN_TYPE_DIVIDE] = "/",
	[TOKEN_TYPE_MODULUS_ASSIGN] = "%=",
	[TOKEN_TYPE_MODULUS] = "%",
	[TOKEN_TYPE_BITWISE_AND_ASSIGN] = "&=",
	[TOKEN_TYPE_BITWISE_AND] = "&",
	[TOKEN_TYPE_BITWISE_OR_ASSIGN] = "|=",
	[TOKEN_TYPE_BITWISE_OR] = "|",
	[TOKEN_TYPE_BITWISE_XOR_ASSIGN] = "^=",
	[TOKEN_TYPE_BITWISE_XOR] = "^",
	[TOKEN_TYPE_BITWISE_NOT_ASSIGN] = "~=",
	[TOKEN_TYPE_BITWISE_NOT] = "~",
	[TOKEN_TYPE_LEFT_SHIFT_ASSIGN] = "<<=",
	[TOKEN_TYPE_LEFT_SHIFT] = "<<",
	[TOKEN_TYPE_RIGHT_SHIFT_ASSIGN] = ">>=",
	[TOKEN_TYPE_RIGHT_SHIFT] = ">>",
	[TOKEN_TYPE_EQUAL] = "==",
	[TOKEN_TYPE_ASSIGN] = "=",
	[TOKEN_TYPE_NOT_EQUAL] = "!=",
	[TOKEN_TYPE_GREATER_EQUAL] = ">=",
	[TOKEN_TYPE_GREATER] = ">",
	[TOKEN_TYPE_LESS_EQUAL] = "<=",
	[TOKEN_TYPE_LESS] = "<",
	[TOKEN_TYPE_LEFT_ANGLE_BRACKET] = "< bracket",
};

const char *const lexer_error_messages[] = {
	[LEXER_ERROR_TYPE_UNRECOGNIZED_TOKEN] = "Unrecognized token.",
	[LEXER_ERROR_TYPE_UNCLOSED_SINGLE_QUOTE] = "Unclosed single quote.",
	[LEXER_ERROR_TYPE_UNCLOSED_DOUBLE_QUOTE] = "Unclosed double quote.",
};
